require 'bundler/gem_tasks'

task :default => [:build_ext, :build]

task :build_ext do
  Dir.chdir '..' do
    sh 'scons'
    sh 'gcc -shared -o ./ruby/rpi_ws281x.so dma.o mailbox.o pwm.o rpihw.o ws2811.o'
  end
end

task :test do
  sh 'sudo ruby client.rb'
end

